name: solar-mirror
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.1.3
  - flask=3.0.0
  - flask-cors=4.0.0
  - pvlib=0.10.3
  - pytz=2023.3
  - pip
  - pip:
      - pytest
